site_name: AIFL Documentation
nav:
  - Home: index.md
  - Core Concepts:
    - Introduction: Core_Concepts/introduction.md
    - Architecture: Core_Concepts/architecture.md
    - Grammar: grammar.md
    - Protocols: protocols.md
    - Symbols: symbols.md
  - Orchestrator:
    - Overview: orchestrator/overview.md
    - Message Flow: orchestrator/message-flow.md
    - Integration Guide: orchestrator/integration-guide.md
    - AIFL Messaging: orchestrator/aifl-messaging.md
    - Monitoring: orchestrator/monitoring.md
    - Scaling: orchestrator/scaling.md
    - Security: orchestrator/security.md
    - Troubleshooting: orchestrator/troubleshooting.md
  - Reference:
    - Glossary: glossary.md
    - Roadmap: roadmap.md
theme: readthedocs
